version: '3.3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  data:
    external: true