version: '3.3'

services:
  database:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
volumes:
  data:
    external: true